# Generated by Django 6.0.2 on 2026-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
