# Generated by Django 6.0.2 on 2026-02-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_profile_is_verified_profile_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='estimated_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
